"""
HTML Report Generator for ASR Model Comparison.

Generates interactive HTML reports with:
- Summary charts and metrics
- Expandable sections for detailed predictions
- Model-by-model comparison
- Per-file results with error highlighting
"""

import os
import json
from datetime import datetime
from typing import List, Dict, Optional
import html


class HTMLReportGenerator:
    """Generates interactive HTML reports for ASR evaluation results."""
    
    def __init__(self, output_dir: str):
        """
        Initialize HTML report generator.
        
        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
    
    def generate(self, results: List[Dict], metadata: Optional[Dict] = None) -> str:
        """
        Generate HTML report from evaluation results.
        
        Args:
            results: List of model evaluation results
            metadata: Optional metadata about the evaluation
            
        Returns:
            Path to generated HTML file
        """
        valid_results = [r for r in results if r is not None]
        
        if not valid_results:
            return None
        
        html_content = self._build_html(valid_results, metadata)
        
        output_path = os.path.join(self.output_dir, "report.html")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return output_path
    
    def _build_html(self, results: List[Dict], metadata: Optional[Dict]) -> str:
        """Build complete HTML document."""
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Prepare chart data
        model_names = [r.get('model_name', 'Unknown') for r in results]
        wer_values = [r.get('avg_wer', 0) * 100 for r in results]  # Convert to percentage
        cer_values = [r.get('avg_cer', 0) * 100 for r in results]
        inference_times = [r.get('avg_inference_time', 0) for r in results]
        
        return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ASR Model Comparison Report</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🎤 ASR Model Comparison Report</h1>
            <p class="timestamp">Generated: {timestamp}</p>
        </header>
        
        {self._build_summary_section(results, metadata)}
        
        {self._build_charts_section(model_names, wer_values, cer_values, inference_times)}
        
        {self._build_comparison_table(results)}
        
        {self._build_detailed_results(results)}
        
        <footer>
            <p>Generated by ASR Evaluation Framework</p>
        </footer>
    </div>
    
    <script>
        {self._get_javascript(model_names, wer_values, cer_values, inference_times)}
    </script>
</body>
</html>'''
    
    def _get_css(self) -> str:
        """Get CSS styles for the report."""
        return '''
        :root {
            --primary-color: #2563eb;
            --success-color: #16a34a;
            --warning-color: #ea580c;
            --danger-color: #dc2626;
            --bg-color: #f8fafc;
            --card-bg: #ffffff;
            --text-color: #1e293b;
            --text-muted: #64748b;
            --border-color: #e2e8f0;
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            line-height: 1.6;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 2rem;
        }
        
        header {
            text-align: center;
            margin-bottom: 2rem;
            padding-bottom: 1rem;
            border-bottom: 2px solid var(--border-color);
        }
        
        header h1 {
            font-size: 2.5rem;
            color: var(--primary-color);
            margin-bottom: 0.5rem;
        }
        
        .timestamp {
            color: var(--text-muted);
            font-size: 0.9rem;
        }
        
        .section {
            background: var(--card-bg);
            border-radius: 12px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        
        .section-title {
            font-size: 1.5rem;
            color: var(--text-color);
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--border-color);
        }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }
        
        .summary-card {
            background: linear-gradient(135deg, var(--primary-color), #3b82f6);
            color: white;
            padding: 1.5rem;
            border-radius: 10px;
            text-align: center;
        }
        
        .summary-card.success {
            background: linear-gradient(135deg, var(--success-color), #22c55e);
        }
        
        .summary-card.warning {
            background: linear-gradient(135deg, var(--warning-color), #f97316);
        }
        
        .summary-card h3 {
            font-size: 0.9rem;
            opacity: 0.9;
            margin-bottom: 0.5rem;
        }
        
        .summary-card .value {
            font-size: 2rem;
            font-weight: bold;
        }
        
        .charts-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 1.5rem;
        }
        
        .chart-container {
            background: var(--card-bg);
            border-radius: 10px;
            padding: 1rem;
            height: 300px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 1rem;
        }
        
        th, td {
            padding: 0.75rem 1rem;
            text-align: left;
            border-bottom: 1px solid var(--border-color);
        }
        
        th {
            background: var(--bg-color);
            font-weight: 600;
            color: var(--text-muted);
            font-size: 0.85rem;
            text-transform: uppercase;
        }
        
        tr:hover {
            background: var(--bg-color);
        }
        
        .badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 500;
        }
        
        .badge-success {
            background: #dcfce7;
            color: var(--success-color);
        }
        
        .badge-warning {
            background: #fef3c7;
            color: var(--warning-color);
        }
        
        .badge-danger {
            background: #fee2e2;
            color: var(--danger-color);
        }
        
        .collapsible {
            background: var(--bg-color);
            border: none;
            width: 100%;
            padding: 1rem;
            text-align: left;
            font-size: 1rem;
            cursor: pointer;
            border-radius: 8px;
            margin-top: 0.5rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            transition: background 0.2s;
        }
        
        .collapsible:hover {
            background: var(--border-color);
        }
        
        .collapsible::after {
            content: '▶';
            font-size: 0.8rem;
            transition: transform 0.2s;
        }
        
        .collapsible.active::after {
            transform: rotate(90deg);
        }
        
        .collapsible-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out;
            background: white;
            border-radius: 0 0 8px 8px;
        }
        
        .collapsible-content.show {
            max-height: none;
            padding: 1rem;
            border: 1px solid var(--border-color);
            border-top: none;
        }
        
        .prediction-item {
            padding: 1rem;
            margin-bottom: 0.5rem;
            background: var(--bg-color);
            border-radius: 8px;
            border-left: 4px solid var(--primary-color);
        }
        
        .prediction-item.error-high {
            border-left-color: var(--danger-color);
        }
        
        .prediction-item.error-medium {
            border-left-color: var(--warning-color);
        }
        
        .prediction-item.error-low {
            border-left-color: var(--success-color);
        }
        
        .prediction-label {
            font-size: 0.8rem;
            color: var(--text-muted);
            margin-bottom: 0.25rem;
        }
        
        .prediction-text {
            font-family: 'Noto Sans Devanagari', sans-serif;
            word-break: break-word;
        }
        
        .prediction-metrics {
            display: flex;
            gap: 1rem;
            margin-top: 0.5rem;
            font-size: 0.85rem;
        }
        
        .metric {
            display: flex;
            align-items: center;
            gap: 0.25rem;
        }
        
        .metric-label {
            color: var(--text-muted);
        }
        
        .best-badge {
            background: gold;
            color: #000;
            padding: 0.2rem 0.5rem;
            border-radius: 4px;
            font-size: 0.75rem;
            margin-left: 0.5rem;
        }
        
        footer {
            text-align: center;
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border-color);
            color: var(--text-muted);
            font-size: 0.9rem;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 1rem;
            }
            
            .charts-grid {
                grid-template-columns: 1fr;
            }
            
            table {
                font-size: 0.85rem;
            }
            
            th, td {
                padding: 0.5rem;
            }
        }
        '''
    
    def _get_javascript(self, model_names: List[str], wer_values: List[float], 
                        cer_values: List[float], inference_times: List[float]) -> str:
        """Get JavaScript for charts and interactivity."""
        return f'''
        // Chart.js configuration
        const modelNames = {json.dumps(model_names)};
        const werValues = {json.dumps(wer_values)};
        const cerValues = {json.dumps(cer_values)};
        const inferenceTimes = {json.dumps(inference_times)};
        
        // WER/CER Comparison Chart
        const ctxMetrics = document.getElementById('metricsChart').getContext('2d');
        new Chart(ctxMetrics, {{
            type: 'bar',
            data: {{
                labels: modelNames,
                datasets: [
                    {{
                        label: 'WER (%)',
                        data: werValues,
                        backgroundColor: 'rgba(37, 99, 235, 0.8)',
                        borderColor: 'rgba(37, 99, 235, 1)',
                        borderWidth: 1
                    }},
                    {{
                        label: 'CER (%)',
                        data: cerValues,
                        backgroundColor: 'rgba(22, 163, 74, 0.8)',
                        borderColor: 'rgba(22, 163, 74, 1)',
                        borderWidth: 1
                    }}
                ]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {{
                    title: {{
                        display: true,
                        text: 'Word Error Rate & Character Error Rate'
                    }}
                }},
                scales: {{
                    y: {{
                        beginAtZero: true,
                        max: 100,
                        title: {{
                            display: true,
                            text: 'Error Rate (%)'
                        }}
                    }}
                }}
            }}
        }});
        
        // Inference Time Chart
        const ctxTime = document.getElementById('timeChart').getContext('2d');
        new Chart(ctxTime, {{
            type: 'bar',
            data: {{
                labels: modelNames,
                datasets: [{{
                    label: 'Avg. Inference Time (s)',
                    data: inferenceTimes,
                    backgroundColor: 'rgba(234, 88, 12, 0.8)',
                    borderColor: 'rgba(234, 88, 12, 1)',
                    borderWidth: 1
                }}]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {{
                    title: {{
                        display: true,
                        text: 'Average Inference Time per File'
                    }}
                }},
                scales: {{
                    y: {{
                        beginAtZero: true,
                        title: {{
                            display: true,
                            text: 'Time (seconds)'
                        }}
                    }}
                }}
            }}
        }});
        
        // Collapsible functionality
        document.querySelectorAll('.collapsible').forEach(button => {{
            button.addEventListener('click', function() {{
                this.classList.toggle('active');
                const content = this.nextElementSibling;
                content.classList.toggle('show');
            }});
        }});
        '''
    
    def _build_summary_section(self, results: List[Dict], metadata: Optional[Dict]) -> str:
        """Build summary statistics section."""
        total_files = sum(r.get('files_processed', 0) for r in results)
        avg_files = total_files // len(results) if results else 0
        
        # Find best model
        best_wer = min(results, key=lambda x: x.get('avg_wer', float('inf')))
        best_cer = min(results, key=lambda x: x.get('avg_cer', float('inf')))
        fastest = min(results, key=lambda x: x.get('avg_inference_time', float('inf')))
        
        return f'''
        <section class="section">
            <h2 class="section-title">📊 Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <h3>Models Evaluated</h3>
                    <div class="value">{len(results)}</div>
                </div>
                <div class="summary-card success">
                    <h3>Files Processed</h3>
                    <div class="value">{avg_files}</div>
                </div>
                <div class="summary-card">
                    <h3>Best WER</h3>
                    <div class="value">{best_wer.get('avg_wer', 0):.2%}</div>
                    <small>{best_wer.get('model_name', 'N/A')}</small>
                </div>
                <div class="summary-card success">
                    <h3>Best CER</h3>
                    <div class="value">{best_cer.get('avg_cer', 0):.2%}</div>
                    <small>{best_cer.get('model_name', 'N/A')}</small>
                </div>
                <div class="summary-card warning">
                    <h3>Fastest Model</h3>
                    <div class="value">{fastest.get('avg_inference_time', 0):.1f}s</div>
                    <small>{fastest.get('model_name', 'N/A')}</small>
                </div>
            </div>
        </section>
        '''
    
    def _build_charts_section(self, model_names: List[str], wer_values: List[float],
                              cer_values: List[float], inference_times: List[float]) -> str:
        """Build charts section."""
        return '''
        <section class="section">
            <h2 class="section-title">📈 Performance Charts</h2>
            <div class="charts-grid">
                <div class="chart-container">
                    <canvas id="metricsChart"></canvas>
                </div>
                <div class="chart-container">
                    <canvas id="timeChart"></canvas>
                </div>
            </div>
        </section>
        '''
    
    def _build_comparison_table(self, results: List[Dict]) -> str:
        """Build model comparison table."""
        # Find best values for highlighting
        best_wer = min(r.get('avg_wer', float('inf')) for r in results)
        best_cer = min(r.get('avg_cer', float('inf')) for r in results)
        best_time = min(r.get('avg_inference_time', float('inf')) for r in results)
        
        rows = ""
        for r in results:
            wer = r.get('avg_wer', 0)
            cer = r.get('avg_cer', 0)
            time = r.get('avg_inference_time', 0)
            
            # Determine badge class based on WER
            if wer < 0.2:
                badge_class = "badge-success"
            elif wer < 0.5:
                badge_class = "badge-warning"
            else:
                badge_class = "badge-danger"
            
            # Add best badge
            wer_badge = '<span class="best-badge">🏆 Best</span>' if wer == best_wer else ''
            cer_badge = '<span class="best-badge">🏆 Best</span>' if cer == best_cer else ''
            time_badge = '<span class="best-badge">⚡ Fastest</span>' if time == best_time else ''
            
            rows += f'''
            <tr>
                <td><strong>{html.escape(r.get('model_name', 'Unknown'))}</strong></td>
                <td>{r.get('model_id', 'N/A')}</td>
                <td>{r.get('files_processed', 0)}</td>
                <td><span class="badge {badge_class}">{wer:.2%}</span>{wer_badge}</td>
                <td>{cer:.2%}{cer_badge}</td>
                <td>{time:.2f}s{time_badge}</td>
                <td>{r.get('total_time', 0):.1f}s</td>
            </tr>
            '''
        
        return f'''
        <section class="section">
            <h2 class="section-title">📋 Model Comparison</h2>
            <table>
                <thead>
                    <tr>
                        <th>Model</th>
                        <th>Model ID</th>
                        <th>Files</th>
                        <th>Avg WER</th>
                        <th>Avg CER</th>
                        <th>Avg Time/File</th>
                        <th>Total Time</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </section>
        '''
    
    def _build_detailed_results(self, results: List[Dict]) -> str:
        """Build detailed per-file results with collapsible sections."""
        sections = ""
        
        for r in results:
            model_name = r.get('model_name', 'Unknown')
            per_file = r.get('per_file_results', [])
            
            if not per_file:
                continue
            
            # Build per-file items
            items = ""
            for pf in per_file[:50]:  # Limit to 50 files for performance
                wer = pf.get('wer', 0)
                cer = pf.get('cer', 0)
                
                # Determine error class
                if wer < 0.2:
                    error_class = "error-low"
                elif wer < 0.5:
                    error_class = "error-medium"
                else:
                    error_class = "error-high"
                
                gt_text = html.escape(pf.get('ground_truth', ''))
                pred_text = html.escape(pf.get('prediction', ''))
                
                items += f'''
                <div class="prediction-item {error_class}">
                    <strong>{html.escape(pf.get('audio_file', 'Unknown'))}</strong>
                    <div class="prediction-metrics">
                        <span class="metric"><span class="metric-label">WER:</span> {wer:.2%}</span>
                        <span class="metric"><span class="metric-label">CER:</span> {cer:.2%}</span>
                        <span class="metric"><span class="metric-label">Time:</span> {pf.get('inference_time', 0):.2f}s</span>
                    </div>
                    <div style="margin-top: 0.75rem;">
                        <div class="prediction-label">Ground Truth:</div>
                        <div class="prediction-text">{gt_text}</div>
                    </div>
                    <div style="margin-top: 0.5rem;">
                        <div class="prediction-label">Prediction:</div>
                        <div class="prediction-text">{pred_text}</div>
                    </div>
                </div>
                '''
            
            more_text = f'<p style="color: var(--text-muted); margin-top: 1rem;">... and {len(per_file) - 50} more files</p>' if len(per_file) > 50 else ''
            
            sections += f'''
            <button class="collapsible">
                <span>📁 {html.escape(model_name)} - {len(per_file)} files</span>
            </button>
            <div class="collapsible-content">
                {items}
                {more_text}
            </div>
            '''
        
        return f'''
        <section class="section">
            <h2 class="section-title">🔍 Detailed Results (Click to Expand)</h2>
            {sections}
        </section>
        '''
